---
- name: Patch Treadmill deps
  file:
    path: "{{app_root}}/etc"
    state: directory

- name: Copy resolv.conf
  copy: remote_src=True src=/etc/resolv.conf dest="{{app_root}}/etc"

- name: Make the mount private
  command: "mount --make-rprivate /"

- name: Configure sshd_config
  replace:
    dest: /etc/ssh/sshd_config
    regexp: "{{item.0}}"
    replace: "{{item.1}}"
    backup: yes
  with_together:
    - ['^#?PermitRootLogin.*','^#?PasswordAuthentication no','^(UsePrivilegeSeparation sandbox.*)']
    - ['PermitRootLogin yes','PasswordAuthentication yes','#\1 \nUsePrivilegeSeparation no']
