---
treadmill_host_ticket: /treadmill/spool/krb5cc_host
broken_nodes_percent: 5%
treadmillid: treadmld
cell: local
zookeeper: zookeeper://foo@127.0.0.1:2181
ldap: ldap://0.0.0.0:1389
ldap_search_base: ou=treadmill,dc=tw,dc=treadmill
masters:
- hostname: localhost.localdomain
  idx: 1
  zk-client-port: 2181
