---
- name: Get Treadmill Binary
  get_url:
    url: "https://github.com/ThoughtWorksInc/treadmill/releases/download/{{treadmill_version}}/treadmill"
    dest: /bin/treadmill
    mode: 0755

- name: Drop the env file
  template: src=env_vars.sh dest="{{ base_dir }}" mode=700

- name: Set treadmill environment variables
  lineinfile:
    dest: ~/.bashrc
    line: "source {{ base_dir }}/env_vars.sh"

- name: Create treadmld user
  user:
    name: treadmld
